# Generated by Django 5.2 on 2025-04-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentIPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
